version: '3.8'

services:
  db:
    image: postgres:17.6-alpine
    container_name: nexus_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - nexus_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  nexus_data: